### ISSUE TITLE
Wrong inventory

### ISSUE THREAD

**Issue by kumy** [geokrety/server-migration#26]
User 30841 has an inventory problem. (Related to #25?)

* GKD5C4, GKD740, GK10154, GKD597, GK100DE are missing from his inventory
* GKFF99, GKF942 are back in his inventory, but they should not.

**Comment by kumy** [comment]
* recalculation of `hand_of` field
* diff between `hand_of` from 2017-12-30 and 2018-01-02

id | OLD | NEW
-- | -- | --
12524 | 6527 | 35743
24371 | 0 | 9773
26183 | 11743 | 10761
27768 | 0 | 20300
45016 | 34883 | 29488
46300 | 21960 | 0
47744 | 38143 | 38162
52602 | 12073 | 0
55416 | 0 | 38159
56176 | 32551 | 28770
57503 | 37944 | 37324
58012 | 25287 | 37324
58308 | 2605 | 32676
58911 | 32693 | 0
60524 | 34186 | 19185
60526 | 34186 | 19185
61190 | 31822 | 34346
62120 | 33602 | 35600
62751 | 26892 | 34346
62752 | 26892 | 34346
62755 | 17286 | 34346
62839 | 3889 | 35065
63387 | 26422 | 0
63545 | 26422 | 38154
63714 | 26422 | 38154
63810 | 28105 | 30841
64614 | 25448 | 32676
64816 | 35065 | 34346
65506 | 19185 | 34186
66100 | 19185 | 34186
66233 | 19185 | 34186

* Manually audited GK history, I've identified those GeoKrety wich may be wrong
https://geokrety.org/konkret.php?id=57503
https://geokrety.org/konkret.php?id=61190
https://geokrety.org/konkret.php?id=62120
https://geokrety.org/konkret.php?id=62752
https://geokrety.org/konkret.php?id=62751
https://geokrety.org/konkret.php?id=62755
https://geokrety.org/konkret.php?id=63810
https://geokrety.org/konkret.php?id=64816

* Will send individual mails to ask for user inventory check.

**Comment by kumy** [comment]
* Mails sent to individual users.

**Comment by kumy** [comment]
@filipsPL @boly38 I would like to publish such news, do you agree? Would you like to change something?

`[GeoKrety] inventory potential issue`

> We have detected a potential problem on GeoKrety users inventory. Problem seems to have started on 2017-12-30. May you please manually compare your GeoKrety physical inventory to the one present on the website (https://geokrety.org/mypage.php?co=5). If you detect some problem, please try to fix GeoKrety move history for example by deleting "bad" logs. If you need assistance, please don't hesitate to contact us. We appologize for the inconvenience. Best wishes for this new year, your GK Team.

> Nous avons detecte probleme potentiel sur les inventaires. le soucis aurait commence le 30-12-2017. Pourriez-vous s'il vous plait, controler mauellement votre inventaire physique de GeoKrety avec celui present sur le site (https://geokrety.org/mypage.php?co=5). Si vous detectez un probleme, merci d'essayer de reparer l'historique des GeoKrety concernes, par exemple en supprimant les deplacement errones ou en trop. N'hesitez pas a nous contacter si vous avez besoin de plus d'aide. Nous sommes desoles pour la gene occasionnee. Nous vous souhaitons tous nos voeux pour cette nouvelle annee, votre equipe GK.

**Comment by kumy** [comment]
* One problem still persists, when deleting logs, `hand_of` field is not recalculated. I'll look into it now.

**Comment by kumy** [comment]
Hope this time the `hands_of` bug is completely fixed.

**Comment by kumy** [comment]
See https://rec.geokrety.org/newscomments.php?newsid=182 for the news proposition.

**Comment by boly38** [comment]
hey

the news content is ok for me

FYI 2 days ago (12/31/2017 🎉) during a maintenance on one of mycache,
c:geo were suggesting me some of mine geokrets hold by another geocacher.
Today while checking 'geokret in my hand' on the website I didn't see any
issue.
So not sure it was bad log issue? dont know.

Anyway 🎉Happy New Year 2018 🎉!

Le 2 janv. 2018 1:41 PM, "kumy" <notifications@github.com> a écrit :

@filipsPL <https://github.com/filipspl> @boly38 <https://github.com/boly38>
I would like to publish such news, do you agree? Would you like to change
something?

[GeoKrety] inventory potential issue

We have detected a potential problem on GeoKrety users inventory. Problem
seems to have started on 2017-12-30. May you please manually compare your
GeoKrety physical inventory to the one present on the website (
https://geokrety.org/mypage.php?co=5). If you detect some problem, please
try to fix GeoKrety move history for example by deleting "bad" logs. If you
need assistance, please don't hesitate to contact us. We appologize for the
inconvenience. Best wishes for this new year, your GK Team.

Nous avons detecte probleme potentiel sur les inventaires. le soucis aurait
commence le 30-12-2017. Pourriez-vous s'il vous plait, controler
mauellement votre inventaire physique de GeoKrety avec celui present sur le
site (https://geokrety.org/mypage.php?co=5). Si vous detectez un probleme,
merci d'essayer de reparer l'historique des GeoKrety concernes, par exemple
en supprimant les deplacement errones ou en trop. N'hesitez pas a nous
contacter si vous avez besoin de plus d'aide. Nous sommes desoles pour la
gene occasionnee. Nous vous souhaitons tous nos voeux pour cette nouvelle
annee, votre equipe GK.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/geokrety/server-migration/issues/26#issuecomment-354758779>,
or mute the thread

**Comment by kumy** [comment]
On 02/01/2018 15:07, Boly38 wrote:
> FYI 2 days ago (12/31/2017 🎉) during a maintenance on one of mycache,
> c:geo were suggesting me some of mine geokrets hold by another geocacher.
> Today while checking 'geokret in my hand' on the website I didn't see any
> issue.
This is exactly the fixed bug here :)
Nice to hear it is/seems fixed.

**Comment by kumy** [comment]
There seems to be problems with GK just born, as seen in userid=38088 inventory

https://geokrety.org/mypage.php?userid=38088&co=5
